# Shell variables
# Generated by 'wal'
wallpaper='/home/hrothgar32/.lightdm_images/vhs_neon.png'

# Special
background='#0B050F'
foreground='#a7c4ef'
cursor='#a7c4ef'

# Colors
color0='#0B050F'
color1='#6C1994'
color2='#5D59DC'
color3='#9717AA'
color4='#A820CC'
color5='#E123E5'
color6='#C757DE'
color7='#a7c4ef'
color8='#7489a7'
color9='#6C1994'
color10='#5D59DC'
color11='#9717AA'
color12='#A820CC'
color13='#E123E5'
color14='#C757DE'
color15='#a7c4ef'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
